---
name: logsearch
update:
  canaries: 1
  canary_watch_time: 30000-1200000
  max_in_flight: 1
  serial: false
  update_watch_time: 5000-1200000

instance_groups:
  - name: elasticsearch_master
    azs: ((elasticsearch_master_azs))
    instances: ((elasticsearch_master_instances))
    persistent_disk_type: ((elasticsearch_master_persistent_disk_type))
    vm_type: ((elasticsearch_master_vm_type))
    stemcell: default
    update:
      max_in_flight: 1
      serial: true
    networks:
      - name: ((elasticsearch_master_network))
    jobs:
      - name: bpm
        release: bpm
      - name: elasticsearch
        release: logsearch
        consumes:
          elasticsearch: {from: elasticsearch_master}
        provides:
          elasticsearch: {as: elasticsearch_master}
        properties:
          elasticsearch:
            node:
              allow_master: true
            config_options: &xpack-options
              xpack.monitoring.enabled: false
              xpack.graph.enabled: false
              xpack.ml.enabled: false
              xpack.security.enabled: false
              xpack.watcher.enabled: false
              xpack.security.transport.ssl.enabled: false

  - name: maintenance
    azs: ((maintenance_azs))
    instances: ((maintenance_instances))
    persistent_disk_type: ((maintenance_persistent_disk_type))
    vm_type: ((maintenance_vm_type))
    stemcell: default
    update:
      serial: true
    networks:
      - name: ((maintenance_network))
    jobs:
      - name: bpm
        release: bpm
      - name: elasticsearch
        release: logsearch
        consumes:
          elasticsearch: {from: elasticsearch_master}
        properties:
          elasticsearch:
            config_options: *xpack-options
      - name: elasticsearch_config
        release: logsearch
        properties:
          elasticsearch_config:
            index_prefix: logs-
            templates:
              - shards-and-replicas: /var/vcap/jobs/elasticsearch_config/index-templates/shards-and-replicas.json
              - index-settings: /var/vcap/jobs/elasticsearch_config/index-templates/index-settings.json
              - index-mappings: /var/vcap/jobs/elasticsearch_config/index-templates/index-mappings.json
      - name: curator
        release: logsearch
      - name: smoke_tests
        release: logsearch
        consumes:
          elasticsearch: {from: elasticsearch_master}
          ingestor_link: {from: ingestor_syslog}

  - name: elasticsearch_data
    azs: ((elasticsearch_data_azs))
    instances: ((elasticsearch_data_instances))
    persistent_disk_type: ((elasticsearch_data_persistent_disk_type))
    vm_type: ((elasticsearch_data_vm_type))
    stemcell: default
    update:
      max_in_flight: 1
      serial: true
    networks:
      - name: ((elasticsearch_data_network))
    jobs:
      - name: bpm
        release: bpm
      - name: elasticsearch
        release: logsearch
        consumes:
          elasticsearch: {from: elasticsearch_master}
        properties:
          elasticsearch:
            node:
              allow_data: true
            config_options: *xpack-options

  - name: kibana
    azs: ((kibana_azs))
    instances: ((kibana_instances))
    persistent_disk_type: ((kibana_persistent_disk_type))
    vm_type: ((kibana_vm_type))
    stemcell: default
    networks:
      - name: ((kibana_network))
    jobs:
      - name: bpm
        release: bpm
      - name: elasticsearch
        release: logsearch
        consumes:
          elasticsearch: {from: elasticsearch_master}
        properties:
          elasticsearch:
            config_options: *xpack-options
      - name: kibana
        release: logsearch
        provides:
          kibana: {as: kibana_link}
        consumes:
          elasticsearch: {from: elasticsearch_master}
        properties:
          kibana:
            health:
              timeout: 500
            env:
              - NODE_ENV: production
            config_options: *xpack-options

  - name: ingestor
    azs: ((ingestor_azs))
    instances: ((ingestor_instances))
    persistent_disk_type: ((ingestor_persistent_disk_type))
    vm_type: ((ingestor_vm_type))
    stemcell: default
    networks:
      - name: ((ingestor_network))
    jobs:
      - name: bpm
        release: bpm
      - name: elasticsearch
        release: logsearch
        consumes:
          elasticsearch: {from: elasticsearch_master}
        properties:
          elasticsearch:
            config_options: *xpack-options
      - name: ingestor_syslog
        release: logsearch
        consumes:
          elasticsearch: nil
        provides:
          ingestor: {as: ingestor_link}
          ingestor_inputs: nil
        properties:
          logstash_parser:
            elasticsearch:
              data_hosts:
                - 127.0.0.1
            deployment_dictionary:
              - /var/vcap/packages/logsearch-config/deployment_lookup.yml

releases:
  - name: logsearch
    # url: https://s3.amazonaws.com/logsearch/logsearch-211.1.0.tgz
    url: https://nextcloud.paas-ta.org/index.php/s/HXTnLT54LeQKges/download
    version: 211.1.0
    # sha1: fa1cd0dc846b163ea619cc0149c2379daee06025
    sha1: 56301fe1178a653b879a502a63698a41b063917c

  - name: bpm
    url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.6
    version: 1.1.6
    sha1: 5bad6161dbbcf068830a100b6a76056fe3b99bc8

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: "latest"

variables: []
